filter:
    excluded_paths:
        - 'assets/*'
        - 'languages/*'
        - 'node_modules/*'
        - 'tests/*'
        - 'vendor/*'
before_commands:
    - 'composer install --dev --prefer-source --ignore-platform-reqs'
checks:
    php: true
    javascript: true
coding_style:
    php:
        indentation:
            general:
                use_tabs: true
        spaces:
            before_parentheses:
                if: false
                for: false
                while: false
                switch: false
                catch: false
            around_operators:
                concatenation: true
            within:
                array_initializer: true
                grouping: true
                function_call: true
                function_declaration: true
                if: true
                for: true
                while: true
                switch: true
                catch: true
        braces:
            classes_functions:
                class: new-line
                function: new-line
                closure: new-line
            if:
                else_on_new_line: true
            do_while:
                while_on_new_line: true
            try:
                catch_on_new_line: true
                finally_on_new_line: true
        upper_lower_casing:
            keywords:
                general: lower
            constants:
                true_false_null: lower
build: true
