language: php

sudo: false

notifications:
  email:
    on_success: never
    on_failure: change

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=4.0 WP_MULTISITE=0

matrix:
  include:
    - php: 5.4
      env: WP_VERSION=latest WP_MULTISITE=1

before_script:
  - bash bin/install.sh wordpress_test root '' localhost $WP_VERSION

script: phpunit
